---
deployment:
    tasks:
        - export DEPLOYPATH=/home/lzmq1c1jdwhe/public_html/index
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp -R img/ $DEPLOYPATH/img/
        - /bin/cp -R style/ $DEPLOYPATH/style/
        - /bin/cp -R js/ $DEPLOYPATH/js/
